### ISSUE TITLE
Keeping transcript and gene information in the same object - gencode

### ISSUE THREAD

**Issue by sorjuela** [mikelove/tximeta#10]
Hi,
I'm using Gencode reference files to `makeLinkedTxome` and run `tximeta`. My problem is that after running `tximeta` I only get transcript information (tx_id) in `rowData`, but I also want the gene information.
This doesn't happen with Ensembl reference files though, meaning in `rowData` you keep both `tx_id` and `gene_id`. So maybe this is a Gencode problem?

**Comment by mikelove** [comment]
The difference is that Ensembl GTFs are brought in by tximeta with ensembldb (pkg specially designed for these files) while the Gencode GTFs are brought in with GenomicFeatures. So it’s upstream of tximeta in that sense, but this sounds like a very good feature to add to tximeta for Gencode. I’ll work on it when I get a chance. For now, I think you can add them easily with addIds(), although cleaner would be to grab them from the GTF on import.

**Comment by mikelove** [comment]
Seems to be addressed by Charlotte's commit
