### ISSUE TITLE
Extracting exon-level information

### ISSUE THREAD

**Issue by kvittingseerup** [mikelove/tximeta#14]
This is so cool!

Would it be possible to also extract the exon-level genomic information? Could be a GRangesList?

**Comment by mikelove** [comment]
Yes the goal would be a GRL in genomic coordinates. 😀

**Comment by mikelove** [comment]
Just added this to devel. And made it pretty fast by caching the exon ranges like we do txp ranges.

I focus on the exon-by-transcript case because I am highly skeptical of the exon-by-gene case.
