### ISSUE TITLE
ID conversion and tximport arguments

### ISSUE THREAD

**Issue by koenvandenberge** [mikelove/tximeta#15]
Hey Mike,

Great package; it's directly useful for our work.
In this post I use four samples from a scRNA-seq dataset, and the Salmon output can be found here: https://www.dropbox.com/sh/lf2wcv9lf3xxke8/AABhYlDymcw_73ja0pvlXhA5a?dl=0

First, for readability of the code, I wanted to add the `txOut` argument to `tximeta`, which however is overwritten internally, so the argument might not be passed along accordingly:

```
> dir <- "~/Dropbox/tximetaMike/"
> samples <- list.files(dir)
> files <- paste0(dir,samples,"/quant.sf")
> names <- samples
> coldata <- data.frame(files,names)
> data <- tximeta(coldata, type="salmon", txOut=TRUE)
importing quantifications
Error in tximport(files, type = type, txOut = TRUE, ...) : 
  formal argument "txOut" matched by multiple actual arguments
```

In addition, the transciptome is not recognized while it's the common human GRCh38 transcriptome (Homo_sapiens.GRCh38.cdna.all.rel80.fa). Do I overlook something?

```
> data <- tximeta(coldata, type="salmon")
importing quantifications
reading in files with read_tsv
1 2 3 4 
couldn't find matching transcriptome, returning un-ranged SummarizedExperiment
```

This might be linked, but I also can't add extra transcsript IDs:

```
> library(org.Hs.eg.db)
> addIds(data, column="GENENAME", gene=FALSE)
Error in addIds(data, column = "GENENAME", gene = FALSE) : 
  requireNamespace(orgpkg.name, quietly = TRUE) is not TRUE
```

**Comment by koenvandenberge** [comment]
Thanks for the reply, very clear now.
Everything works as a charm after running `makeLinkedTxome`,  which was very easy.

Thanks for making all our lifes easier :-).

**Comment by koenvandenberge** [comment]
The `CHL1` gene was one of my special interests in this dataset.
While I did find it with manually converting the IDs, I do not seem to find it with `addIds`:

```
> library(org.Hs.eg.db)
> se <- addIds(se, column="ALIAS")
mapping to new IDs using 'org.Hs.eg.db' data package
grep(x=rowData(se)$ALIAS,pattern="^CHL1")

> grep(x=rowData(se)$ALIAS,pattern="^CHL1")
integer(0)
> 
> 
> hlpId <- ensembldb::select(x=org.Hs.eg.db, keys=rownames(assays(se)$counts), keytype="ENSEMBLTRANS", columns="ALIAS")
'select()' returned 1:many mapping between keys and columns
> grep(x=hlpId$ALIAS, pattern="^CHL1")
 [1] 16235 16238 16241 16244 16247 16250 16253 16256 16259 16262 16265 16268
[13] 16271 16274 16277 16280
```

**Comment by mikelove** [comment]
Version 1.1.1 now has helpful (hopefully) errors for `txOut=FALSE` when `type="salmon"` and for `summarizeToGene` or `addIds` when the metadata is missing.

Here's the commit:

601dfc8c673e7ee62aaa0ec5f6f47467ef8e7d1a

**Comment by mikelove** [comment]
For the second error, it looks like I should be using `ensembldb::select` here:

https://github.com/mikelove/tximeta/blob/master/R/addIds.R#L33-L34

Can you give me one of these ENST transcript IDs so I can debug?

**Comment by koenvandenberge** [comment]
```
c("ENST00000256509", "ENST00000481167", "ENST00000397491", "ENST00000427688",
 "ENST00000421198", "ENST00000489224", "ENST00000453040", "ENST00000435603",
 "ENST00000486881", "ENST00000461289", "ENST00000471332", "ENST00000470880",
 "ENST00000445697", "ENST00000620033")
```

**Comment by mikelove** [comment]
I see the problem:

```
> select(org.Hs.eg.db, "ENST00000256509", "ALIAS", "ENSEMBLTRANS")
'select()' returned 1:many mapping between keys and columns
     ENSEMBLTRANS  ALIAS
1 ENST00000256509   CALL
2 ENST00000256509 L1CAM2
3 ENST00000256509   CHL1
> select(org.Hs.eg.db, "ENST00000256509", "SYMBOL", "ENSEMBLTRANS")
'select()' returned 1:1 mapping between keys and columns
     ENSEMBLTRANS SYMBOL
1 ENST00000256509   CHL1
```

I am using `mapIds` which picks the first. The alternative would be to give back a *CharacterList*, but these are a bit awkward to deal with. What do you think? Note that SYMBOL gives CHL1 alone.

**Comment by koenvandenberge** [comment]
Great, thanks for digging this up.
If there are multiple mappings, it might be worth stating a warning that there are, because now it kind of occurs without the user realizing it, and that by default `mapIds` only picks one. It can be useful if the user would be able to retrieve the multimappings with an extra argument. 
You could indeed use the `multiVals` argument to return a CharacterList of all mappings, if desired.

**Comment by koenvandenberge** [comment]
It seems to occur for ˜12% of the transcripts in the transcriptome I'm looking at.

**Comment by mikelove** [comment]
I’ll just let the user pass through multiVals specification I think. I’ll go with the default value (ensembldb does the same).

It’s very often the case that there are 1:many mappings so I can print a friendly message about multiVals.

**Comment by mikelove** [comment]
I just pushed version 1.1.2:

```
 > se <- addIds(se, "SYMBOL")
 mapping to new IDs using 'org.Hs.eg.db' data package
 if all matching IDs are desired, and '1:many mappings' are reported,
 set multiVals='list' to obtain all the matching IDs
 'select()' returned 1:many mapping between keys and columns
 > head(mcols(se)$SYMBOL)
 ENST00000456328 ENST00000450305 ENST00000488147 ENST00000619216 ENST00000473358 ENST00000469289
       "DDX11L1"       "DDX11L1"              NA              NA              NA              NA
```

And then with `multiVals=TRUE`:

```
 > se <- addIds(se, "SYMBOL", multiVals="list")
 mapping to new IDs using 'org.Hs.eg.db' data package
 if all matching IDs are desired, and '1:many mappings' are reported,
 set multiVals='list' to obtain all the matching IDs
 'select()' returned 1:many mapping between keys and columns
 > head(mcols(se)$SYMBOL)
 $ENST00000456328
 [1] "DDX11L1"
...
 > class(mcols(se)$SYMBOL)
 [1] "list"
```

Two other changes is that it will load the org package on its own if it doesn't find it (avoiding error) and it will switch to gene automatically if the first row looks like "ENSG...":

```
 > gse <- addIds(gse, "SYMBOL")
 mapping to new IDs using 'org.Hs.eg.db' data package
 if all matching IDs are desired, and '1:many mappings' are reported,
 set multiVals='list' to obtain all the matching IDs
 it appears the rows are gene IDs, setting 'gene' to TRUE
 'select()' returned 1:many mapping between keys and columns
```
