### ISSUE TITLE
Paired txomes (human + mouse Gencode)

### ISSUE THREAD

**Issue by mikelove** [mikelove/tximeta#16]
For single cell experiments, we sometimes use pairs of txomes as the reference. With some extra work, we could output two objects, where we pick apart the human and mouse txomes. This would probably be a specific feature only supporting Gencode pairs.

**Comment by mdshw5** [comment]
I’ve been saying for 2 years now that our PISCES pipeline will be open source, but I have been supporting generalized combinations of transcriptomes in the fashion and it’s really useful for chimeric models as well as custom additions like engineered transcripts and viral elements.

**Comment by mikelove** [comment]
Interesting, yeah, there are also folks here at UNC who add in viral sequences, etc. I think `linkedTxome` makes sense here (similar to what you do with PISCES). But it will need to split out two objects which have different `genome` metadata maybe. For now I'm putting this off while I do other low hanging fruit.

**Comment by mikelove** [comment]
I don't think this will be feasible anymore, as we will encounter issues with seqnames from different organisms. I think the safest is to push this back to the user, where the GTF should be modified to clearly indicate the origin of the transcripts (e.g. human vs mouse chr1 will need to be indicated in the GTF/GFF).
