### ISSUE TITLE
error in addIds

### ISSUE THREAD

**Issue by AnnaSawicka** [mikelove/tximeta#17]
Hi Mike,
I have a problem with adding REFSEQ IDs to the SummarizedExperiment object, containing ENSEMBL transcripts and quantification information from Salmon. I have a tximeta_1.0.3 version. I used makeLinkedTxome:

indexPath <-"/usr/users/asawick/ania/U2OS_4sU_060319/salmon/Homo_sapiens.GRCh38.cdna.all_index"
fastaPath <-"/usr/users/asawick/ania/U2OS_4sU_060319/salmon/Homo_sapiens.GRCh38.cdna.all.fa"
gtfPath <- "/usr/users/asawick/ania/U2OS_4sU_060319/salmon/Homo_sapiens.GRCh38.96.gtf" 

makeLinkedTxome(indexDir=indexPath,
                source="Ensembl",
                organism="Homo Sapiens",
                release="38",
                genome="GRCh",
                fasta=fastaPath,
                gtf=gtfPath,
                write=FALSE)

The object (st in this case) looks ok:
> rowRanges(st)
GRanges object with 168526 ranges and 6 metadata columns:
                  seqnames              ranges strand |           tx_id
                     <Rle>           <IRanges>  <Rle> |     <character>
  ENST00000434970       14   22439007-22439015      + | ENST00000434970
  ENST00000448914       14   22449113-22449125      + | ENST00000448914
  ENST00000415118       14   22438547-22438554      + | ENST00000415118
  ENST00000604446       15   21010494-21010516      - | ENST00000604446
  ENST00000603693       15   21011451-21011469      - | ENST00000603693
              ...      ...                 ...    ... .             ...
  ENST00000635145       20   29878636-29879363      - | ENST00000635145
  ENST00000617915        1 159972548-159974064      - | ENST00000617915
  ENST00000455649        X 133989443-133990086      + | ENST00000455649
  ENST00000278882       20   30377372-30399257      + | ENST00000278882
  ENST00000644453        9 131370933-131372514      + | ENST00000644453
                              tx_biotype tx_cds_seq_start tx_cds_seq_end
                             <character>        <integer>      <integer>
  ENST00000434970              TR_D_gene         22439007       22439015
  ENST00000448914              TR_D_gene         22449113       22449125
  ENST00000415118              TR_D_gene         22438547       22438554
  ENST00000604446              IG_D_gene         21010494       21010516
  ENST00000603693              IG_D_gene         21011451       21011469
              ...                    ...              ...            ...
  ENST00000635145 unprocessed_pseudogene             <NA>           <NA>
  ENST00000617915 unprocessed_pseudogene             <NA>           <NA>
  ENST00000455649 unprocessed_pseudogene             <NA>           <NA>
  ENST00000278882 unprocessed_pseudogene             <NA>           <NA>
  ENST00000644453 unprocessed_pseudogene             <NA>           <NA>
                          gene_id         tx_name
                      <character>     <character>
  ENST00000434970 ENSG00000237235 ENST00000434970
  ENST00000448914 ENSG00000228985 ENST00000448914
  ENST00000415118 ENSG00000223997 ENST00000415118
  ENST00000604446 ENSG00000270824 ENST00000604446
  ENST00000603693 ENSG00000270451 ENST00000603693
              ...             ...             ...
  ENST00000635145 ENSG00000283020 ENST00000635145
  ENST00000617915 ENSG00000273933 ENST00000617915
  ENST00000455649 ENSG00000232068 ENST00000455649
  ENST00000278882 ENSG00000149531 ENST00000278882
  ENST00000644453 ENSG00000285287 ENST00000644453
  -------
  seqinfo: 47 sequences from GRCh38 genome
>

But I get the following error:
library("org.Hs.eg.db")
> st <-addIds(st, column = "REFSEQ", gene = F)
Error in addIds(st, column = "REFSEQ", gene = F) :
  requireNamespace(orgpkg.name, quietly = TRUE) is not TRUE

Do you maybe know what I'm overlooking?

Thank you,
Anna

**Comment by federicomarini** [comment]
Do you have the `org.Hs.eg.db` package installed? The error message seems to point at that?

**Comment by AnnaSawicka** [comment]
Thank for your quick response. yes, the package is installed. 
This is my sessionInfo, it's in "other attached packages" :
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.3 (Nitrogen)

Matrix products: default
BLAS: /home/mpg05/asawick/tools/R-3.5.3/lib64/R/lib/libRblas.so
LAPACK: /home/mpg05/asawick/tools/R-3.5.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
[1] org.Hs.eg.db_3.7.0   AnnotationDbi_1.44.0 IRanges_2.16.0
[4] S4Vectors_0.20.1     Biobase_2.42.0       BiocGenerics_0.28.0
[7] tximeta_1.0.3

**Comment by mikelove** [comment]
I'd prefer if we could switch to Bioconductor support site for these questions:

support.bioconductor.org

Please just post the above question and tag "tximeta"
