### ISSUE TITLE
multiple sample input with type = "alevin"

### ISSUE THREAD

**Issue by csoneson** [mikelove/tximeta#20]
Providing multiple sample input with type = "alevin" does not seem to work with the current call to `getMetaInfo` (since `getMetaInfo` assumes a single input file): 

https://github.com/mikelove/tximeta/blob/6e87c9b37e5cba359abdf93ac9b052643a2642ec/R/tximeta.R#L155-L157

I didn't check yet whether there are other things implying that this should just not be done (in which case it might be better to check immediately that `coldata` has only one line for alevin input), or whether `getMetaInfo` should be called separately for each input file also for alevin.

**Comment by mikelove** [comment]
Aha yeah I should put a check ahead of this that there’s just one file. I didn’t intent to support more than one (yet).

**Comment by mikelove** [comment]
There is such a check in tximport, which I will port over.

**Comment by mikelove** [comment]
Thanks, fixed with 5b63dd2c00aade451a44c4d133e736a47b76b8a1
