### ISSUE TITLE
Error: Could not connect to database:

### ISSUE THREAD

**Issue by Knievl** [mikelove/tximeta#25]
Hello,

as soon as i run tximeta, it is unable to connect to database, i tested the FTP url on my own and its perfectly fine. How can i solve this?

Best regards

```
 se <- tximeta(coldata)
 importing quantifications
 reading in files with read_tsv
 1 
 found matching transcriptome:
 [ Ensembl - Drosophila melanogaster - release 97 ]
 loading existing EnsDb created: 2020-01-18 13:16:29
 Error: Could not connect to database:
 unable to open database file
```

**Comment by mikelove** [comment]
It looks like there's a problem with your pre-existing EnsDb, that it got wiped out somehow or corrupted.

One thing you could do is to go into the BiocFileCache and remove this EnsDb entry so it will be downloaded again.

```
library(BiocFileCache)
bfc <- BiocFileCache()
bfcinfo(bfc)
bfcremove(bfc, rids="...")
```

Where you should fill in the `rids` that matches the EnsDb.

**Comment by mikelove** [comment]
I'm going to close this, but feel free to re-open if the above doesn't fix.
