### ISSUE TITLE
biocache file problem

### ISSUE THREAD

**Issue by klai001** [mikelove/tximeta#28]
Hi Mike
Coldata was formatted as exactly according to the html tutorial.
I have just tried running tximeta(coldata)..it was running until it gives me the following notification..

------------------------------------
#when i select 1 -use default
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning messages:
1: In dir.create(tximetaDir) :
  cannot create dir 'C:\Users\LIMPEC~1\AppData\Local\tximeta\tximeta\Cache', reason 'No such file or directory'
2: In file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:\Users\LIMPEC~1\AppData\Local\tximeta\tximeta\Cache/bfcloc.json': No such file or directory
##note that I am running Rstudio as administrator and my BioFileCache is up till date
##i then created a new bfc
> bfc <-BiocFileCache(path)
> bfccache(bfc)
[1] "C:/Users/Google Drive/Phd/Project-based Planning and protocols/LPS Study/LPS bulk RNAseq analysis/rhistory"
> setTximetaBFC(bfccache(bfc))
## again same error popped up
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning messages:
1: In dir.create(tximetaDir) :
  cannot create dir 'C:\Users\LIMPEC~1\AppData\Local\tximeta\tximeta\Cache', reason 'No such file or directory'
2: In file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:\Users\LIMPEC~1\AppData\Local\tximeta\tximeta\Cache/bfcloc.json': No such file or directory
--------------------------

## when i select 2- use temp
Selection: 2
found matching transcriptome:
[ Ensembl - Mus musculus - release 99 ]
building EnsDb with 'ensembldb' package
Importing GTF file ... trying URL 'ftp://ftp.ensembl.org/pub/release-99/gtf/mus_musculus/Mus_musculus.GRCm38.99.gtf.gz'
Error in download.file(resource(con), destfile) : 
  cannot open URL 'ftp://ftp.ensembl.org/pub/release-99/gtf/mus_musculus/Mus_musculus.GRCm38.99.gtf.gz'
##therefore i followed the MakelinkTxome function as stated in your tutorial
and manged to get the message 
## saving linkedTxome in bfc (first time)
##i then re-run tximeta(coldata)
but same error persists

**Comment by mikelove** [comment]
Could you repost this on the Bioc support site? That’s my preferred location for bugs like this. I tend to use GitHub Issues for feature requests. I’ll reply quickly there.

**Comment by klai001** [comment]
Hi Mike
I've posted it there. https://support.bioconductor.org/p/128462/
I'm sorry w the formatting; still pretty new to all this.

thanks,
Best
Kei
