### ISSUE TITLE
Customized import of alevin bootstrap counts

### ISSUE THREAD

**Issue by k3yavi** [mikelove/tximeta#32]
Hi @mikelove ,

I think it'd great to have a new parameter in the `alevinArgs` which can be tweaked for importing the `mean` and the `variance` bootstrap estimate matrix. Currently, if alevin is run with `numCellBootstraps` , tximeta will always import the mean and the variance of the matrices, along with the MLE estimates. I think it's great to load all the matrices most of the time, however, it'd be valuable to have a flag which can control this behavior for the cases where we need quick testing !

btw did I say tximeta is super fast !! :D

**Comment by mikelove** [comment]
This should be covered by `alevingArgs=list(dropMeanVar)` in *tximport* v1.17.2.

Also while I was poking around, I remembered I have the notice that:

> pre-v0.14.0 Alevin import will be deprecated in October 2020

Does that sound ok? It's a lot of extra code, unit tests, and testing data that is no longer used.
