### ISSUE TITLE
Issue with finding matching exome/makeLinkedTxome

### ISSUE THREAD

**Issue by malawsky** [mikelove/tximeta#33]
Hello,

Thank you for making a fantastic rna seq analysis pipeline!

I ran Salmon using the following transcriptome:

> ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz

Salmon ran perfectly fine on all my samples. However, I am trying to use tximeta to prepare the data for DESeq2 analysis yet when I run tximeta I get:

`couldn't find matching transcriptome, returning un-ranged SummarizedExperiment`

I tried using makeLinkedTxome but it gives me an error when trying to pass it my local salmon index directory:

```
Error: lexical error: invalid char in json text.
                                      /proj/gershont/projects/salmon/a
                    (right here) ------^
```

Thank you very much for your help!

Best,
Danny

**Comment by mikelove** [comment]
Can you post your version? If you are using the latest or second latest version of Bioc it should work automatically. I.e. tximeta version 1.6.1 or 1.4.1.

(That should fix it, but also the other issue you posted involves [updating](https://github.com/jeroen/jsonlite/issues/106) jsonlite)

**Comment by malawsky** [comment]
I am running version tximport_1.10.1, is that the wrong one?

**Comment by malawsky** [comment]
I am running version tximeta_1.0.3. Do I need to update it then?

**Comment by mikelove** [comment]
In that 1.0 < 1.4, yes 😉

**Comment by malawsky** [comment]
it worked! thank you!
