### ISSUE TITLE
couldn't find matching transcriptome, returning un-ranged SummarizedExperiment

### ISSUE THREAD

**Issue by sunliang3361** [mikelove/tximeta#35]
Hi Mike,
I used Mouse M24 transcript.fa from gencode at ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M24/gencode.vM24.transcripts.fa.gz, which was in your hash table https://github.com/mikelove/tximeta/blob/master/inst/extdata/hashtable.csv.

Do you know what my problem is? Thanks,

Liang

--

> suppressPackageStartupMessages(library(SummarizedExperiment))
> se <- tximeta(coldata)
importing quantifications
reading in files with read_tsv
1 2 3 4 5 6 7 8 9 10 11 12 
couldn't find matching transcriptome, returning un-ranged SummarizedExperiment

**Comment by mikelove** [comment]
Usually this is because someone is using an older version of the package.

**Comment by mikelove** [comment]
For example, see #33

**Comment by sunliang3361** [comment]
Thank you so much for your quick response. I solve this problem after updating tximeta version but have another error message. Can you give some hints?

> y
class: RangedSummarizedExperiment 
dim: 140948 6 
metadata(6): tximetaInfo quantInfo ... txomeInfo txdbInfo
assays(3): counts abundance length
rownames(140948): ENSMUST00000193812.1 ENSMUST00000082908.1 ... ENSMUST00000082422.1 ENSMUST00000082423.1
rowData names(3): tx_id gene_id tx_name
colnames(6): A1 A2 ... D2 D3
colData names(3): names condition type
> y$condition
[1] "adequate"  "adequate"  "adequate"  "deficient" "deficient" "deficient"
> y$type
[1] "Female" "Female" "Female" "Female" "Female" "Female"
> y <- scaleInfReps(y)
Error in infRepError(infRepIdx) : 
  there are no inferential replicates in the assays of 'y'

**Comment by mikelove** [comment]
Can we continue with any follow ups on the support site? I’m going to mark this tximeta issue as closed.

If you are trying to use fishpond, note the fishpond vignette details about generating inferential replicates.
