### ISSUE TITLE
Error in splitSE

### ISSUE THREAD

**Issue by cnk113** [mikelove/tximeta#36]
Hello,

I accidentally updated some packages along with tximeta, and when I run splitSE to split the counts into spliced and unspliced counts I get the error.
txis <- splitSE(txi, cg, assayName = "counts")
Where cg has two columns, spliced and unspliced.
```Error in (function (x)  : attempt to apply non-function```
I'm assuming the error is rather recent since this was after I accidentally updated it.
For reference I'm following the alevin velocity [tutorial](https://combine-lab.github.io/alevin-tutorial/2020/alevin-velocity/).

Thanks,
Chang

**Comment by mikelove** [comment]
Could you post to support.bioconductor.org with sessionInfo() and we’ll look into it.
