### ISSUE TITLE
Request: addCDS() function

### ISSUE THREAD

**Issue by kvittingseerup** [mikelove/tximeta#42]
Would it be possible for tximeta to also support extracting the CDS regions associated with each transcript? Would be fairly straight forward since both TxDb and EnsDb support the cdsBy() function.

Cheers
Kristoffer

**Comment by mikelove** [comment]
Interesting idea. I’m not sure where to put the regions in the SE. If they replace the rowRanges, there are transcripts that don’t have a CDS so what to do for those?

**Comment by mikelove** [comment]
I suppose the GRanges could go in mcols(se)?

**Comment by kvittingseerup** [comment]
Guess it could be either

- A GRangeList (like exons) with NA for non-coding as `rowRanges(se)`
- Extending `rowData(se)` / `mcols(se)` with the genomic start/end coordinates (then people can obtain the exon level CDS data by using `GenomicRanges::restrict()` on the result of `addExons` and the newly added genomic coordinates )

**Comment by mikelove** [comment]
Thanks! I’ll take a look at implementing ASAP

**Comment by mikelove** [comment]
I took a shot at adding this in 95c94af

Let me know if it works on your end. I put in some important details in the man page, because GRangesList cannot have `NA`, I use the original ranges to fill in the empty slots for the non-coding transcripts, and then I'm just noisy about this in messaging.

**Comment by kvittingseerup** [comment]
Works beautifully :D
