### ISSUE TITLE
batch processing compatibility

### ISSUE THREAD

**Issue by stolarczyk** [mikelove/tximeta#45]
hi @mikelove,

I'm writing a vignette that calls `tximeta` function and discovered there's no way to make the prompt decisions upfront. Therefore the knitting process hangs once it gets to this function call.

Is batch processing compatibility something you are willing to enable for `tximeta`? I expect this might be useful outside of my use case.

**Comment by mikelove** [comment]
Do you mean the question about where to store the cache? I believe we have two solutions.

You can either do `setTximetaBFC`:

https://rdrr.io/bioc/tximeta/man/getTximetaBFC.html

Or you could use the environmental variable solution proposed by Charlotte:

https://github.com/mikelove/tximeta/issues/31

**Comment by stolarczyk** [comment]
thanks! yes, `setTximetaBFC` eliminates one of the prompts I've been getting. There's another one concerning AnnotationHub cache directory creation, in case it does not exist. For my use case I can set `useHub=FALSE`, though.

**Comment by mikelove** [comment]
The other one can be avoided also with the AHub environmental variable (see AnnotationHub man pages).
