### ISSUE TITLE
Bioconda version still 1.6.2

### ISSUE THREAD

**Issue by matmu** [mikelove/tximeta#47]
I would like to add tximeta to my Docker container by installing it via Conda. The version in Bioconda is still 1.6.2 (https://anaconda.org/bioconda/bioconductor-tximeta), although there is already the more recent version 1.6.3 available. With 1.6.2 I am facing problems to automatically recognize the transcriptome I am using. Could you please update it to 1.6.3 or tell me who I have to approach? Thanks a lot.

**Comment by mikelove** [comment]
This is outside of my scope (I don't maintain the bioconda versions).

One solution is that you could add the transcriptome you are using via `makeLinkedTxome()`. It's just one function call and then your transcriptome will be recognized and tximeta functions will work as if you were using 1.6.3.

**Comment by matmu** [comment]
@mikelove 
Thanks for your help. I was able to update the bioconda version of tximeta myself today.
I am already using `makeLinkedTxome()` as a workaround. Is there any speed difference between `makeLinkedTxome()` and the automated mode?

**Comment by mikelove** [comment]
No speed difference, tximeta is doing a few things: read in the data with tximport, lookup the checksum in the table to find a match, compile the metadata (which may involve possibly downloading and possibly parsing a file, or using a cached version of the file or database), packaging the output.
