### ISSUE TITLE
Error with 'download.file' on Linux cluster

### ISSUE THREAD

**Issue by lmweber** [mikelove/tximeta#48]
This is a really amazing package, which has made some of our work much easier, thanks!

However I did get one error when running it on our Linux cluster, which I thought I would report here.

The error occurs when downloading genome info. I suspect it is a problem with running the base command `download.file` on a Linux cluster, although I am not completely sure. I know `download.file` has problems on Windows too.

The error message is as follows. It all works fine when running on my Mac laptop instead.

```
fetching genome info for GENCODE
Error in download.file(url, destfile, quiet = TRUE) : 
  cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'
> download.file("http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz", destfile = "./testing.txt.gz", quiet = TRUE)
Error in download.file("http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz",  : 
  cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'
```

**Comment by lmweber** [comment]
Oh, now it has worked! I logged out and back into our cluster, and tried again.

Maybe it was related to creating the cache directory for the first time.

Ok I think this is a non-issue then, sorry! I'll close the issue.

**Comment by mikelove** [comment]
I think it could have been an internet issue. 

The genome info is a weak point, as the core mechanism for Bioc functions to get the genome info is via this USCS link. I think Ahub solves it, as we just grab the correct db with seqinfo. Maybe you GENCODE wasn’t in Ahub though? (Or are you using 3.11?)
