### ISSUE TITLE
couldn't find matching transcriptome, returning non-ranged SummarizedExperiment

### ISSUE THREAD

**Issue by Artanis-tera** [mikelove/tximeta#50]
Hi Mike, 
My tximeta version is 1.8.1 but I still met the error "couldn't find matching transcriptome, returning non-ranged SummarizedExperiment" when I tried to use   " library(tximeta)   se=coldata2" .  Here is my coldata2, its file.path worked properly
![image](https://user-images.githubusercontent.com/72880084/100172928-5fe2b600-2f04-11eb-8e92-9ee177170d51.png)
I am very confused so would you please help me to figure it out?
plus, I've no idea why my "quant.sf" files, which are produced by salmon quant command, are kind of odd. Their head lines are as follows. Maybe that is the point?
![image](https://user-images.githubusercontent.com/72880084/100173316-370ef080-2f05-11eb-90ec-60511be996ed.png)
Too much thanks!

**Comment by mikelove** [comment]
Can you take a look at #38 and confirm that your version of the transcriptome is in the set represented here:

https://bioconductor.org/packages/release/bioc/vignettes/tximeta/inst/doc/tximeta.html#Pre-computed_checksums

**Comment by mikelove** [comment]
It looks like you quantified against chromosomes, not transcripts from that file.

**Comment by Artanis-tera** [comment]
Oh, I see... A mistake...
Thank you very much!
