### ISSUE TITLE
tximeta UCSC not co-operating in terms of mm10

### ISSUE THREAD

**Issue by justinjacobse** [mikelove/tximeta#58]
(Edit: title of issue is supposed to be "tximeta and UCSC not co-operating in terms of mm10")

Hello, when I try to run tximeta, I get this error:

fetching genome info for GENCODE
Error in .order_seqlevels(chrom_sizes[, "chrom"]) : 
  !anyNA(m31) is not TRUE

I found that others have had a similar problem when using GenomeInfoDb due to UCSC releasing a patch update for mm10 (see https://github.com/Bioconductor/GenomeInfoDb/issues/27 and https://www.biostars.org/p/9477823/)

They provide a workaround, but I don't know how to integrate the workaround with tximeta.

I am using tximeta 1.8.2, and I know the most recent version is 1.11.2. Is this issue fixed in the new version? (If not, I would rather not update it because every time I update a package in R, another package stops working).

Thank you!

**Comment by mikelove** [comment]
You can either use skipSeqinfo=TRUE, which avoids using USCS to grab seq info, or you can get the latest version of GenomeInfoDb which resolves the issue (the issue you linked to is now closed by Herve).

**Comment by justinjacobse** [comment]
Thank you so much! skipSeqinfo=TRUE worked perfectly.
