### ISSUE TITLE
Getting "couldn't find matching transcriptome" with Gencode 40

### ISSUE THREAD

**Issue by jwtobias** [mikelove/tximeta#64]
Counted with Salmon v 1.8.0 against human Gencode 40 (released 4/11/22) and getting the error below. When do you typically capture the gencode releases?

> packageVersion("tximeta")
[1] '1.12.4'

> se <- tximeta(coldata)
importing quantifications
reading in files with read_tsv
1 2 3 4 5 6 
couldn't find matching transcriptome, returning non-ranged SummarizedExperiment

**Comment by mikelove** [comment]
Oh I just missed this one. Let me push this one through now. Thanks for the note.

**Comment by mikelove** [comment]
I just pushed to GH, could you try `devtools::install_github("mikelove/tximeta")` and see if this works (you may need to restart R)?

**Comment by jwtobias** [comment]
All good now. Thanks for the quick response and the great tool!
