### ISSUE TITLE
Error in checkAssays2Txps

### ISSUE THREAD

**Issue by karlaarz** [mikelove/tximeta#66]
Hello, 

I am trying to import some Salmon data using tximeta but I get the following error:
```
Error in checkAssays2Txps(assays, txps) : 
  none of the transcripts in the quantification files are in the GTF
```
My script goes as following:
```
indexDir <- file.path(dir, "salmon_idx_zebrafish")
fastaFTP <- "http://ftp.ensembl.org/pub/release-105/fasta/danio_rerio/cdna/Danio_rerio.GRCz11.cdna.all.fa.gz"
gtfPath <- "http://ftp.ensembl.org/pub/release-105/gtf/danio_rerio/Danio_rerio.GRCz11.105.gtf.gz"
makeLinkedTxome(indexDir=indexDir, source="Ensembl_FTP", organism="Danio rerio",
                release="105", genome="GRCz11", fasta=fastaFTP, gtf=gtfPath, write=FALSE)

se <- tximeta(coldata, type = "salmon", useHub=FALSE)
importing quantifications
reading in files with read_tsv
1 2 3 4 5
found matching linked transcriptome:
[ Ensembl_FTP - Danio rerio - release 105 ]
loading existing TxDb created: 2022-06-06 19:02:42
loading existing transcript ranges created: 2022-06-06 19:02:43
Error in checkAssays2Txps(assays, txps) :
 none of the transcripts in the quantification files are in the GTF
```

I am using tximeta v1.14.0 and the R version 4.2.0 (2022-04-22).

Any help would be appreciated.

Thanks

**Comment by mikelove** [comment]
Can you post the starting few lines of a quant.sf file and also a few lines from the Ensembl GTF. Sometimes Ensembl has a slightly different naming scheme between GTF and FASTA.

**Comment by mikelove** [comment]
Also in the meantime you can use skipMeta=TRUE if you don’t need the genomic ranges right now.

**Comment by mikelove** [comment]
I think if you specify `ignoreTxVersion = TRUE` it may also be able to connect the FASTA to GTF.

tximeta/tximport don't do any guessing of the matches (just because there are so many different sources, and we don't want to make a mistake by assuming any bit of an identifier is insignificant). But we do have some options to help deal with inconsitencies in the source files.

**Comment by karlaarz** [comment]
Hi Mike, yes, by adding `ignoreTxVersion = TRUE ` and `skipMeta=TRUE ` options now it runs smoothly. Thanks for the help!
