### ISSUE TITLE
Unsuccessful connection to AnnotationHub blocks tximeta on HPC

### ISSUE THREAD

**Issue by danilotat** [mikelove/tximeta#67]
Hi Mike, thanks for your work on this package. 
I've used it many times with success, till now when I'm facing a problem with its usage in a HPC server. Obviously I've checked for internet connection and, while checking for suggested solution outside I came across this [issue](https://github.com/Bioconductor/AnnotationHub/issues/20) on AnnotationHub. It seems to reflect my scenario, where on our cluster `nslookup` requests are blocked by default. 
Is there any existing workaround ?  
I'm using `tximeta=1.14.0` installed from Bioconda.
Here's the stdout
```
NOTE: linkedTxome with source='Ensembl', ensembldb will be used to parse GTF.
this may produce errors if the GTF is not from Ensembl, or has been modified.
set useHub=FALSE in tximeta to avoid download of reference txome from AnnotationHub.
alternatively use a different string for source argument
writing linkedTxome to /hpc/../salmon_index_GRCh38_ensembl.json
saving linkedTxome in bfc (first time)
importing quantifications
reading in files with read.delim (install 'readr' package for speed up)
1 2
found matching linked transcriptome:
[ Ensembl - Homo sapiens - release 105 ]
useHub=TRUE: checking for EnsDb via 'AnnotationHub'
Cannot connect to AnnotationHub server, using 'localHub=TRUE' instead
Error in .updateHubDB(hub_bfc, .class, url, proxy, localHub) :
  Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Calls: tximeta ... AnnotationHub -> .Hub -> .create_cache -> .updateHubDB
Execution halted
```

**Comment by mikelove** [comment]
useHub=FALSE should fix?

**Comment by danilotat** [comment]
It works, although I'm still seeing many errors coming from unsuccessful connections with `ftp.ensemblgenomes.org`: sorry for such an annoying issue. Which is the impact of using/not using AnnotationHub?

**Comment by mikelove** [comment]
Tximeta extends tximport in two ways: 1) it packages the matrices into a Bioconductor (S4) object and 2) it automatically downloads metadata based on inferring the provenance of the transcripts.

If you don’t have ftp access then (2) won’t work. You can still take advantage of (1) by setting skipMeta=TRUE.

**Comment by mikelove** [comment]
The AHub aspect isn’t really relevant. Tximeta works with or without AHub…

**Comment by danilotat** [comment]
Fine, thanks for the quick response. I’ll close this issue
