### ISSUE TITLE
Renaming duplicate transcripts for Ensembl

### ISSUE THREAD

**Issue by mikelove** [mikelove/tximeta#7]
Don't use the haplotype chromosome transcript ID, but figure out the one on the "standard chromosome"

**Comment by stephenturner** [comment]
see also COMBINE-lab/salmon#249 @afkoeppel

**Comment by mikelove** [comment]
I’ve hopefully fixed this with e29c460

**Comment by mikelove** [comment]
Details: cleanDuplicateTxps=TRUE will swap out haplotype chromosome transcripts for standards chromsome transcripts that are exact sequence duplicates. Needs some testing which I will do this week but let me know if it works for you.
