### ISSUE TITLE
Support for `oarfish` quants

### ISSUE THREAD

**Issue by mikelove** [mikelove/tximeta#81]

**Comment by gringer** [comment]
Here's some oarfish output from samples that I processed yesterday; they are counts from 4 different groups of mouse immune cells, no replicates, mapped against the Gencode M34 transcriptome using minimap2 v2.27:

BP04 - CD11b-hi; Nb+
BP05 - CD11b-hi; Nb-
BP06 - CD11b-low; Nb+
BP07 - CD11b-low; Nb-

[oarfish_output_2024-Mar-22.tar.gz](https://github.com/thelovelab/tximeta/files/14729679/oarfish_output_2024-Mar-22.tar.gz)

**Comment by mikelove** [comment]
Cool, i'll work on it this week. thanks David!

**Comment by rob-p** [comment]
Cool! Let me know if you need help. You can check the piscem inplementation and use that code directly for loading onf reps, I think.

**Comment by mikelove** [comment]
tximport devel branch:

https://github.com/thelovelab/tximport/commit/7b1fbe4bffc98c21e891a37c5a0e1751a85045ba

**Comment by mikelove** [comment]
Ok should be supported now, no changes needed in tximeta.

**Comment by stubbsrl** [comment]
Thanks for this great tool! Will oarfish support be pushed to the main branch anytime soon?

**Comment by mikelove** [comment]
This change was pushed into Bioconductor devel branch in March so it has been in the past two releases (Apr '24 and Oct '24).

**Comment by stubbsrl** [comment]
Oh the error is on my end! Thanks for the quick reply! 

For anyone else who ends up here confused why there installation didn't include oarfish, I had to update to a newer version of R to use a newer version of bioconductor to get the newer release of tximport (I did everything in a conda env). I also needed to install r arrow.
