### ISSUE TITLE
Tximeta does not recognize prebuild TxDb objects for custom transcriptomes

### ISSUE THREAD

**Issue by alexdhill** [mikelove/tximeta#82]
I have a workflow for recreating custom salmon indexes using novel transcript annotations, and during the "build reference" stage of my work I generate a transcriptome `(*.fa.gz)`, an annotation `(*.gtf.gz)` and make a salmon index from the transcriptome file. At this stage I also use tximeta to create a linkedTranscriptome file, and the TxDb package to make a TxDb object.

The problem is when I run my samples through the quantification portion of the workflow, I aggregate all the `salmon quant` results using tximeta. Before this I explicity import the linkedTxome and TxDb object I generated into the working R environment. tximeta detects my linkedTxome, but does not recognize the TxDb object and attempts to compute a new one using the GTF. This will technically work, but the transcriptome I am using is *very* large and I don't want to recompute it for every batch of samples I run. I assume there is some linkage step run when the TxDb object is created from the `tximeta::tximeta` call that I need to be doing explicitly?

**Comment by alexdhill** [comment]
Managed to solve it, tximeta saves the TxDb objects in the BiocFileCache location (see below code from `tximeta.R`)
```
saveDb(
        txdb,
        file = bfcnew(bfc, rname=txdbName, ext=".sqlite")
      )
```

Doing the same allows tximeta to find prebuild TxDb objects.

**Comment by mikelove** [comment]
You got it. I was about to post the same.
