### ISSUE TITLE
Error when running tximeta with full salmon output

### ISSUE THREAD

**Issue by charlesfoster** [mikelove/tximeta#84]
Hello,

I ran some RNAseq samples through the `nf-core/rnaseq` workflow. I'm now intending to conduct differential expression analyses in R after reading in the counts using `tximeta`, but I am receiving an error. For each sample, the `nf-core/rnaseq` workflow outputs the full `salmon` output directory. I'm using this as the input for my `tximeta` command, but I get the following:

```r
coldata <- read.table("Tximeta_Input_Spreadsheet_tmp.csv", header=TRUE, sep=",", stringsAsFactors = FALSE)
se <- tximeta(coldata)

Error in customAuxDir(dir, auxDir) : 
  metadata files are missing, tximeta requires the full Salmon/piscem output files
```

Supporting information:

```r
> head(coldata)
     files    names condition
1 ACV_REP1 ACV_REP1       ACV

```
* files: relative path to the full directory from `salmon`
* names: the replicate name
* conditions: the condition  to be tested

(note: there are other samples and conditions, I've just restricted it to one sample for the purposes of this post)

The contents of the `salmon` output directory:

```
$ tree ACV_REP1/
ACV_REP1/
├── aux_info
│   ├── ambig_info.tsv
│   ├── exp3_pos.gz
│   ├── exp3_seq.gz
│   ├── exp5_pos.gz
│   ├── exp5_seq.gz
│   ├── expected_bias.gz
│   ├── exp_gc.gz
│   ├── fld.gz
│   ├── meta_info.json
│   ├── obs3_pos.gz
│   ├── obs3_seq.gz
│   ├── obs5_pos.gz
│   ├── obs5_seq.gz
│   ├── observed_bias_3p.gz
│   ├── observed_bias.gz
│   ├── obs_gc.gz
│   └── unmapped_names.txt
├── cmd_info.json
├── Homo_sapiens.GRCh38.dna_sm.primary_assembly.filtered.gtf
├── lib_format_counts.json
├── libParams
│   └── flenDist.txt
├── logs
│   └── salmon_quant.log
├── quant.genes.sf
└── quant.sf

3 directories, 24 files
```

```
$ cat ACV_REP1/cmd_info.json 
{
    "salmon_version": "1.10.3",
    "geneMap": "Homo_sapiens.GRCh38.dna_sm.primary_assembly.filtered.gtf",
    "threads": "6",
    "libType": "ISR",
    "index": "salmon",
    "mates1": "ACV_REP1_1.fastp.fastq.gz",
    "mates2": "ACV_REP1_2.fastp.fastq.gz",
    "writeUnmappedNames": [],
    "seqBias": [],
    "gcBias": [],
    "posBias": [],
    "output": "ACV_REP1",
    "auxDir": "aux_info"
}
```

```
$ cat ACV_REP1/aux_info/meta_info.json 
{
    "salmon_version": "1.10.3",
    "samp_type": "none",
    "opt_type": "vb",
    "quant_errors": [],
    "num_libraries": 1,
    "library_types": [
        "ISR"
    ],
    "frag_dist_length": 1001,
    "frag_length_mean": 211.5334755050848,
    "frag_length_sd": 78.54362816090557,
    "seq_bias_correct": true,
    "gc_bias_correct": true,
    "num_bias_bins": 4096,
    "mapping_type": "mapping",
    "keep_duplicates": false,
    "num_valid_targets": 387001,
    "num_decoy_targets": 194,
    "num_eq_classes": 1001520,
    "serialized_eq_classes": false,
    "eq_class_properties": [
        "range_factorized",
        "gzipped"
    ],
    "length_classes": [
        541,
        733,
        1086,
        2011,
        347561
    ],
    "index_seq_hash": "cbc16b736d3c5fcf7e9ce6b77ec896394c90cd4107e2309c405c7924053fe233",
    "index_name_hash": "aa9a32fb8f5358410e277f76f9f36dcdb8d468bc462a0d7806907ebabd64de85",
    "index_seq_hash512": "05b21fcc084306c2a95c9054d00e4c539952713064e36e9a2564de17fc84b558afc5aa114f0ea7d343ec383b4d7d20e5084426e74cadcb05a59f71d5ab50a23a",
    "index_name_hash512": "b1689fc11cf11362d0798157724f4caa719a459dc2dadbb65d4bb14f0764faa1cbcaab3e14d3412d09aaca0dc1f6a7af6c43b3b02050205f2d0b9e727bdcd001",
    "index_decoy_seq_hash": "dba0cfeab270ee576723fa2f1ee2f4dc408b1cbfedc677478c8ca067aabc7ba0",
    "index_decoy_name_hash": "01c56669eed27669376eefee85477e65d513bd953a64fd8ee76277dbdf8f47d4",
    "num_bootstraps": 0,
    "num_processed": 51372292,
    "num_mapped": 39697857,
    "num_decoy_fragments": 2699782,
    "num_dovetail_fragments": 210908,
    "num_fragments_filtered_vm": 3057336,
    "num_alignments_below_threshold_for_mapped_fragments_vm": 14091096,
    "percent_mapped": 77.27484107580794,
    "call": "quant",
    "start_time": "Tue Nov 12 12:23:32 2024",
    "end_time": "Tue Nov 12 12:46:43 2024"
}
```

There is a [similar prior post][1] on this, but in my case I believe I have the correct directory input (rather than just the quant.sf file), so I can't figure out what is going wrong. When I DO just use the quant.sf files the command works, but obviously I just get the "couldn't find matching transcriptome, returning non-ranged SummarizedExperiment" message. Any help would be appreciated.

```r
> sessionInfo()
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Pop!_OS 22.04 LTS
<truncated>

> packageVersion("tximeta")
[1] '1.24.0'

```

p.s. I tried posting this to Bioconductor but for whatever reason it just wouldn't post

  [1]: https://support.bioconductor.org/p/9159161/ "similar prior post"

**Comment by mikelove** [comment]
In the docs `files` includes the ending of the abundance file.

**Comment by charlesfoster** [comment]
Thanks for the fast reply. I guess I didn't entirely understand the previous message printed by `tximeta` when I _did_ include the ending of the abundance file:

```r
> coldata <- read.table("Tximeta_Input_Spreadsheet.csv", header=TRUE, sep=",", stringsAsFactors = FALSE)
> head(coldata)
                                                                                                      files    names
1 ACV_REP1/quant.sf ACV_REP1
2 ACV_REP2/quant.sf ACV_REP2
3 ACV_REP3/quant.sf ACV_REP3
4 GCV_REP1/quant.sf GCV_REP1
5 GCV_REP2/quant.sf GCV_REP2
6 GCV_REP3/quant.sf GCV_REP3
  condition
1       ACV
2       ACV
3       ACV
4       GCV
5       GCV
6       GCV

> se <- tximeta(coldata)
importing quantifications
reading in files with read_tsv
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 
couldn't find matching transcriptome, returning non-ranged SummarizedExperiment
```

In some previous posts around Github/Bioconductor I saw that it might be because of users not copying the full Salmon output, but I _had_ copied the full output, so I thought perhaps I needed to give the path to the directory. I'm not sure why it isn't working (with the full path to quant.sf files) for me given that  I built the Salmon index using the Ensembl HG38 genome + GTF files, and  I thought that Ensembl worked "[out of the box](https://support.bioconductor.org/p/127877/)".

In any case, I've followed the [instructions](https://bioconductor.org/packages/release/bioc/vignettes/tximeta/inst/doc/tximeta.html#Running_tximeta) to `makeLinkedTxome` ,  and this appeared to work, so I'll close this.

**Comment by mikelove** [comment]
Got it. This above means that the hash of the transcriptome is not present in the known transcriptomes to tximeta.

Do you know where this is from:

`Homo_sapiens.GRCh38.dna_sm.primary_assembly.filtered.gtf`

**Comment by charlesfoster** [comment]
I initially got the GTF file from Ensembl using the instructions recommended by `nf-core/rnaseq`:

```sh
latest_release=$(curl -s 'http://rest.ensembl.org/info/software?content-type=application/json' | grep -o '"release":[0-9]*' | cut -d: -f2)
wget -L ftp://ftp.ensembl.org/pub/release-${latest_release}/gtf/homo_sapiens/Homo_sapiens.GRCh38.${latest_release}.gtf.gz
```

The name change of the GTF occurs during the workflow execution in a filtering process:

> GTF filtering
By default, the input GTF file will be filtered to ensure that sequence names correspond to those in the genome fasta file, and to remove rows with empty transcript identifiers.

The transcripts fasta is prepared using the filtered gtf file + the Ensembl assembly with `rsem`:

```sh
rsem-prepare-reference \
    --gtf Homo_sapiens.GRCh38.dna_sm.primary_assembly.filtered.gtf \
    --num-threads 12 \
     \
    rsem/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa \
    rsem/genome
```

Then the `salmon` index is created like so:

```sh
grep '^>' Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa | cut -d ' ' -f 1 | cut -d $'\t' -f 1 > decoys.txt
sed -i.bak -e 's/>//g' decoys.txt
cat genome.transcripts.fa Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa > gentrome.fa

salmon \
    index \
    --threads 6 \
    -t gentrome.fa \
    -d decoys.txt \
    -k 31 \
    -i salmon
```

I'm assuming now that any of these intermediate steps might mess up the transcriptome hash, meaning that it doesn't automatically work with `tximeta`. Of course if this is the case then this is more a workflow problem than a `tximeta` problem.

Cheers,
Charles

**Comment by mikelove** [comment]
Got it. Thanks for letting me know.

yeah we use either straight GENCODE or straight Ensembl txps -- either coding or coding + noncoding. But no filtering or resorting.
